const mockProjects = [
  {
    name: 'Project Name 1',
    type: 'Commercial',
    user: 'John Doe',
    location: 'Lahore',
    status: 'Completed',
    total: '$234',
    date: 'Oct 2, 2020',
    image: 'https://via.placeholder.com/50',
  },
  {
    name: 'Project Name 2',
    type: 'Non-Commercial',
    user: 'Jane Smith',
    location: 'Karachi',
    status: 'Cancelled',
    total: '$120',
    left: '$34',
    date: 'Oct 3, 2020',
    image: 'https://via.placeholder.com/50',
  },
  {
    name: 'Project Name 3',
    type: 'Commercial',
    user: 'Alice Johnson',
    location: 'Islamabad',
    status: 'On Going',
    total: '$500',
    left: '$200',
    date: 'Oct 4, 2020',
    image: 'https://via.placeholder.com/50',
  },
  {
    name: 'Project Name 4',
    type: 'Non-Commercial',
    user: 'Bob Brown',
    location: 'Lahore',
    status: 'Pending',
    total: '$450',
    date: 'Oct 5, 2020',
    image: 'https://via.placeholder.com/50',
  },
  {
    name: 'Project Name 5',
    type: 'Commercial',
    user: 'Charlie White',
    location: 'Peshawar',
    status: 'Completed',
    total: '$300',
    date: 'Oct 6, 2020',
    image: 'https://via.placeholder.com/50',
  },
  {
    name: 'Project Name 6',
    type: 'Non-Commercial',
    user: 'Eve Black',
    location: 'Quetta',
    status: 'Cancelled',
    total: '$180',
    left: '$50',
    date: 'Oct 7, 2020',
    image: 'https://via.placeholder.com/50',
  },
  {
    name: 'Project Name 7',
    type: 'Commercial',
    user: 'Dave Wilson',
    location: 'Lahore',
    status: 'On Going',
    total: '$600',
    left: '$250',
    date: 'Oct 8, 2020',
    image: 'https://via.placeholder.com/50',
  },
  {
    name: 'Project Name 8',
    type: 'Non-Commercial',
    user: 'John Legend',
    location: 'Karachi',
    status: 'Pending',
    total: '$400',
    date: 'Oct 9, 2020',
    image: 'https://via.placeholder.com/50',
  },
  {
    name: 'Project Name 9',
    type: 'Commercial',
    user: 'Michael Green',
    location: 'Islamabad',
    status: 'Completed',
    total: '$500',
    date: 'Oct 10, 2020',
    image: 'https://via.placeholder.com/50',
  },
  {
    name: 'Project Name 10',
    type: 'Non-Commercial',
    user: 'Sara Brown',
    location: 'Lahore',
    status: 'Cancelled',
    total: '$320',
    left: '$70',
    date: 'Oct 11, 2020',
    image: 'https://via.placeholder.com/50',
  },
  {
    name: 'Project Name 11',
    type: 'Commercial',
    user: 'Paul Young',
    location: 'Peshawar',
    status: 'On Going',
    total: '$700',
    left: '$300',
    date: 'Oct 12, 2020',
    image: 'https://via.placeholder.com/50',
  },
  {
    name: 'Project Name 12',
    type: 'Non-Commercial',
    user: 'Laura King',
    location: 'Quetta',
    status: 'Pending',
    total: '$380',
    date: 'Oct 13, 2020',
    image: 'https://via.placeholder.com/50',
  },
];

export default mockProjects;
